version: '3'

services:
  jenkins:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
  agent:
    image: jenkinsci/jnlp-slave:alpine
    environment:
      JENKINS_URL: "http://jenkins:8080"
      JENKINS_SECRET: "5e0e21af79c7d8c2559d635d57491dd0fd78ec422f26e759c4add3628e434a46"
      JENKINS_AGENT_NAME: agent
    links:
      - jenkins
