version: '3'

services:
  jenkins:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
  #agent:
    #build:
      #context: ./agent
